name: Show System Info

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  show-info:
    runs-on: ubuntu-latest

    steps:
    - name: Show system info
      uses: mochaaP/neofetch-action@master
