name: Show System Info

on:
  push:
    branches:
      - main
  workflow_dispatch: # Manual trigger

jobs:
  show-info:
    runs-on: ubuntu-latest

    steps:
    - name: Show system info
      uses: mochaaP/neofetch-action@master

    - name: Display Ubuntu version
      run: |
        lsb_release -a
